- hosts: all
  user: root
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Add a list of users
    user: name={{ item }} state=present group=wheel
    with_items:
      - dhoni
      - virat
      - yuvraj
      - paparao
      - kalyan
  - name: Remove the list of users
    user: name={{ item }} state=absent
    with_items:
      - virat
      - yuvraj
