--- # RUNONCE PLAYBOOK EXAMPLE

- hosts: all
  user: root
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Run the uptime command on all hosts and log it
      raw: /usr/bin/uptime >> /root/logs/uptime.log
      #run_once: true
      ignore_errors: yes
    - name: List the /var directory and log it
      raw: ls -al /var >> /root/logs/dir.list
      #run_once: true
      #ignore_errors: yes
